package com.mininetworks.game.audio

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import com.mininetworks.game.R
import com.mininetworks.game.data.GameIo
import com.mininetworks.game.game.Service
import com.mininetworks.game.game.SoundCue
import kotlin.math.pow

/** The game's sound effects: small WAV files in `res/raw`, generated by `SoundSynth` in the unit tests. */
enum class Sound(val res: Int, val volume: Float) {
    /** Soft pluck on every delivery, pitched per service ([ServicePitch]). */
    PLUCK(R.raw.sfx_pluck, 0.45f),
    /** A cable snapped into place (laid or repaired). */
    CABLE(R.raw.sfx_cable, 0.7f),
    /** A device starts to overload; pitched up and louder as its ring fills ([Alarm]). */
    WARNING(R.raw.sfx_warning, 0.8f),
    /** The game is lost. */
    GAME_OVER(R.raw.sfx_gameover, 0.85f),
    /** A new week begins. */
    CHIME(R.raw.sfx_week, 0.6f),
}

/**
 * Each service plucks its own note of a C major pentatonic scale around the recorded C5, so a busy network plays a
 * chord instead of noise. Values are [SoundPool] playback rates (0.5..2).
 */
object ServicePitch {
    fun rate(service: Service): Float = 2.0.pow(semitones(service) / 12.0).toFloat()

    fun semitones(service: Service): Int = when (service) {
        Service.CLOUD_BACKUP -> -5
        Service.MAIL -> 0
        Service.CALL -> 2
        Service.GAMING -> 4
        Service.STREAMING -> 7
        Service.VIDEO_CALL -> 9
        Service.CAMERA_UPLOAD -> 12
    }
}

/**
 * The rising alarm: the overload warning replayed higher and louder at each stage of a filling ring, so the ear hears
 * the danger grow without a new sound to learn. Rates are [SoundPool] playback rates, volumes scale [Sound.volume].
 */
object Alarm {
    /** A minor third up at half a ring. */
    val HALF_RATE: Float = 2.0.pow(3 / 12.0).toFloat()
    /** A fifth up, at full volume, at [com.mininetworks.game.game.SoundCues.CRITICAL_RING]. */
    val CRITICAL_RATE: Float = 2.0.pow(7 / 12.0).toFloat()
    const val HALF_VOLUME = 1.1f
    const val CRITICAL_VOLUME = 1.25f
}

/**
 * Plays [Sound]s through a [SoundPool] that lives from [open] to [close] (the activity's resume to pause). Nothing plays
 * while [enabled] is false. Plucks of one service closer together than [MIN_PLUCK_GAP_MS] are dropped, so a burst of
 * deliveries stays a soft patter; different services at once make a chord.
 *
 * Creating the pool and loading the files is audio and disk work: [open] leaves it to the [GameIo] thread and returns
 * at once (docs/TOP100.md A3); sounds asked for before the pool is ready are skipped. [open] and [close] are called on
 * the UI thread, [play] on the game thread.
 */
class SoundPlayer(private val context: Context) {
    @Volatile var enabled = true

    /** A ready pool with the stream ids of its loaded [Sound]s, by ordinal. */
    private class Loaded(val pool: SoundPool, val ids: IntArray)

    private val lock = Any()
    /** True between [open] and [close]; a pool that finishes loading after [close] is released at once. */
    private var wanted = false // guarded by lock
    @Volatile private var loaded: Loaded? = null
    private val lastPluck = LongArray(Service.entries.size) { Long.MIN_VALUE / 2 }

    /** The last sounds played (at most [HISTORY]), with their rate, oldest first; for tests. */
    internal val played = ArrayDeque<Pair<Sound, Float>>()

    /** The effective volume of each of [played]; for tests. */
    internal val volumes = ArrayDeque<Float>()

    /** True once the pool is loaded and sounds are heard; for tests. */
    internal val ready get() = loaded != null

    fun open() {
        synchronized(lock) {
            if (wanted) return
            wanted = true
        }
        GameIo.execute {
            val attrs = AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_GAME)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build()
            val pool = SoundPool.Builder().setMaxStreams(MAX_STREAMS).setAudioAttributes(attrs).build()
            val ids = IntArray(Sound.entries.size)
            Sound.entries.forEach { ids[it.ordinal] = pool.load(context, it.res, 1) }
            val keep = synchronized(lock) {
                (wanted && loaded == null).also { if (it) loaded = Loaded(pool, ids) }
            }
            if (!keep) pool.release()
        }
    }

    fun close() {
        val old = synchronized(lock) {
            wanted = false
            loaded.also { loaded = null }
        }
        old?.pool?.release()
    }

    /** Plays the sound for a cue from the world; [nowMs] is a monotonic clock for the pluck gap. */
    fun play(cue: SoundCue, nowMs: Long) {
        when (cue) {
            is SoundCue.Delivered -> {
                val i = cue.service.ordinal
                if (nowMs - lastPluck[i] < MIN_PLUCK_GAP_MS) return
                if (play(Sound.PLUCK, ServicePitch.rate(cue.service))) lastPluck[i] = nowMs
            }
            SoundCue.OverloadStarted -> play(Sound.WARNING)
            SoundCue.OverloadHalf -> play(Sound.WARNING, Alarm.HALF_RATE, Alarm.HALF_VOLUME)
            SoundCue.OverloadCritical -> play(Sound.WARNING, Alarm.CRITICAL_RATE, Alarm.CRITICAL_VOLUME)
            SoundCue.GameOver -> play(Sound.GAME_OVER)
            SoundCue.NewWeek -> play(Sound.CHIME)
        }
    }

    /** Plays [sound] at [rate] and [gain] times its own volume (capped at full); false if sound is off. */
    fun play(sound: Sound, rate: Float = 1f, gain: Float = 1f): Boolean {
        if (!enabled) return false
        val v = (sound.volume * gain).coerceAtMost(1f)
        played.addLast(sound to rate)
        volumes.addLast(v)
        if (played.size > HISTORY) {
            played.removeFirst()
            volumes.removeFirst()
        }
        loaded?.let { it.pool.play(it.ids[sound.ordinal], v, v, if (sound == Sound.PLUCK) 0 else 1, 0, rate) }
        return true
    }

    private companion object {
        const val MAX_STREAMS = 8
        const val MIN_PLUCK_GAP_MS = 60L
        const val HISTORY = 64
    }
}
