package com.mininetworks.game.audio

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import com.mininetworks.game.R
import com.mininetworks.game.game.Service
import com.mininetworks.game.game.SoundCue
import kotlin.math.pow

/** The game's sound effects: small WAV files in `res/raw`, generated by `SoundSynth` in the unit tests. */
enum class Sound(val res: Int, val volume: Float) {
    /** Soft pluck on every delivery, pitched per service ([ServicePitch]). */
    PLUCK(R.raw.sfx_pluck, 0.45f),
    /** A cable snapped into place (laid or repaired). */
    CABLE(R.raw.sfx_cable, 0.7f),
    /** A device starts to overload. */
    WARNING(R.raw.sfx_warning, 0.8f),
    /** A new week begins. */
    CHIME(R.raw.sfx_week, 0.6f),
}

/**
 * Each service plucks its own note of a C major pentatonic scale around the recorded C5, so a busy network plays a
 * chord instead of noise. Values are [SoundPool] playback rates (0.5..2).
 */
object ServicePitch {
    fun rate(service: Service): Float = 2.0.pow(semitones(service) / 12.0).toFloat()

    fun semitones(service: Service): Int = when (service) {
        Service.CLOUD_BACKUP -> -5
        Service.MAIL -> 0
        Service.CALL -> 2
        Service.GAMING -> 4
        Service.STREAMING -> 7
        Service.VIDEO_CALL -> 9
        Service.CAMERA_UPLOAD -> 12
    }
}

/**
 * Plays [Sound]s through a [SoundPool] that lives from [open] to [close] (the activity's resume to pause). Nothing plays
 * while [enabled] is false. Plucks of one service closer together than [MIN_PLUCK_GAP_MS] are dropped, so a burst of
 * deliveries stays a soft patter; different services at once make a chord.
 */
class SoundPlayer(private val context: Context) {
    @Volatile var enabled = true
    private var pool: SoundPool? = null
    private val ids = IntArray(Sound.entries.size)
    private val lastPluck = LongArray(Service.entries.size) { Long.MIN_VALUE / 2 }

    /** The last sounds played (at most [HISTORY]), with their rate, oldest first; for tests. */
    internal val played = ArrayDeque<Pair<Sound, Float>>()

    fun open() {
        if (pool != null) return
        val attrs = AudioAttributes.Builder()
            .setUsage(AudioAttributes.USAGE_GAME)
            .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
            .build()
        pool = SoundPool.Builder().setMaxStreams(MAX_STREAMS).setAudioAttributes(attrs).build().also { p ->
            Sound.entries.forEach { ids[it.ordinal] = p.load(context, it.res, 1) }
        }
    }

    fun close() {
        pool?.release()
        pool = null
    }

    /** Plays the sound for a cue from the world; [nowMs] is a monotonic clock for the pluck gap. */
    fun play(cue: SoundCue, nowMs: Long) {
        when (cue) {
            is SoundCue.Delivered -> {
                val i = cue.service.ordinal
                if (nowMs - lastPluck[i] < MIN_PLUCK_GAP_MS) return
                if (play(Sound.PLUCK, ServicePitch.rate(cue.service))) lastPluck[i] = nowMs
            }
            SoundCue.OverloadStarted -> play(Sound.WARNING)
            SoundCue.NewWeek -> play(Sound.CHIME)
        }
    }

    /** Plays [sound] at [rate]; false if sound is off. */
    fun play(sound: Sound, rate: Float = 1f): Boolean {
        if (!enabled) return false
        played.addLast(sound to rate)
        if (played.size > HISTORY) played.removeFirst()
        pool?.play(ids[sound.ordinal], sound.volume, sound.volume, if (sound == Sound.PLUCK) 0 else 1, 0, rate)
        return true
    }

    private companion object {
        const val MAX_STREAMS = 8
        const val MIN_PLUCK_GAP_MS = 60L
        const val HISTORY = 64
    }
}
